apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: task-api
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers: # <--- ATENÇÃO: Deve estar alinhado dentro de 'spec'
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        args: ["--requirepass", "minhasenhaforte"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"